(() => {
  const D = window.STUDY_DATA;
  const $ = (s, el=document) => el.querySelector(s);
  const $$ = (s, el=document) => [...el.querySelectorAll(s)];
  const main = $('#main');

  const LS = {
    done:'study.done', theme:'study.theme', notes:'study.notes',
    mastery:'study.v2.mastery', review:'study.v2.review', wrong:'study.v2.wrong',
    activity:'study.v2.activity', exams:'study.v2.examHistory', cases:'study.v2.caseHistory',
    goals:'study.v3.learningGoals'
  };

  const readJSON = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)); } catch { return fallback; } };
  const state = {
    done: new Set(readJSON(LS.done, [])),
    theme: localStorage.getItem(LS.theme) || 'light',
    mastery: readJSON(LS.mastery, {}),
    review: readJSON(LS.review, {}),
    wrong: readJSON(LS.wrong, {}),
    activity: readJSON(LS.activity, []),
    exams: readJSON(LS.exams, []),
    caseHistory: readJSON(LS.cases, {}),
    goals: readJSON(LS.goals, {}),
    exam:null, reviewRun:null, caseRun:null, guideRun:null,
    timers:[]
  };
  document.documentElement.dataset.theme = state.theme;

  const esc = (s='') => String(s).replace(/[&<>'"]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const moduleById = id => D.modules.find(m => m.id === id);
  const now = () => Date.now();
  const dayMs = 86400000;
  const todayKey = (d=new Date()) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const hash = s => { let h=2166136261; for (let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)} return (h>>>0).toString(36); };
  const shuffle = arr => { const a=[...arr]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; };
  const pct = (a,b) => b ? Math.round(a/b*100) : 0;

  function persist(key, val){ localStorage.setItem(key, JSON.stringify(val)); }
  function clearTimers(){ state.timers.forEach(clearInterval); state.timers=[]; }
  function toast(msg){ const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2200); }

  function noteActivity(){
    const k=todayKey(); if(!state.activity.includes(k)){state.activity.push(k);state.activity=state.activity.slice(-90);persist(LS.activity,state.activity);}
  }
  noteActivity();

  function streak(){
    const set=new Set(state.activity); let n=0; const d=new Date(); d.setHours(12,0,0,0);
    while(set.has(todayKey(d))){n++;d.setDate(d.getDate()-1);} return n;
  }

  function inferTopic(objOrText){
    if(objOrText && typeof objOrText==='object' && objOrText.topic) return objOrText.topic;
    const s=(typeof objOrText==='string' ? objOrText : `${objOrText?.q||''} ${objOrText?.e||''}`).toLowerCase();
    const rules=[
      ['LRV',/\blrv\b|rättspsyki|\bsup\b/],
      ['LPT',/\blpt\b|\baps\b|vårdintyg|psykiatrisk tvång|intagningsbeslut/],
      ['LVM',/\blvm\b|pl 12 a|missbrukare.*tvång|socialnämnd.*missbruk/],
      ['Handräckning',/handräck|\bpl 20\b|tillträde.*bostad/],
      ['Narkotika',/\bnsl\b|rb 28|kroppsbesikt|husrannsakan|eget bruk|medhjälp.*bruk|olovlig.*narkotika/],
      ['Kommunikation',/förändringstrapp|aktivt lyss|parafras|empati|fakta.*känsl|konflikt/],
      ['Krisstöd',/krisstöd|psykologisk första hjälp|tjänstevapen/],
      ['Psykos',/psykos|schizofren|hallucination|vanföreställ|negativa symtom|positiva symtom|neolog/],
      ['Affektiva',/depression|mani|bipol|nedstämd|sömnbehov|suicid/],
      ['NPF',/adhd|autism|npf|ouppmärksam|hyperaktiv/],
      ['Personlighet',/personlighet|borderline|antisocial|kluster [abc]/],
      ['Beroende',/benso|cannabis|amfetamin|opiat|hallucinogen|abstinens|beroende|pupill|centraldepress|centralstim/]
    ];
    return (rules.find(([,r])=>r.test(s))||['Grunder'])[0];
  }
  function topicMeta(topic){ return D.topicMeta?.[topic] || {label:topic,source:'Kursmaterial'}; }
  function allTopics(){ return Object.keys(D.topicMeta||{}).filter(t=>t!=='Grunder').concat('Grunder'); }
  function masteryFor(topic){ const m=state.mastery[topic]||{correct:0,total:0}; return {...m,pct:pct(m.correct,m.total)}; }
  function updateMastery(topic, correct){
    const m=state.mastery[topic]||{correct:0,total:0}; m.total++; if(correct)m.correct++; m.updated=Date.now(); state.mastery[topic]=m; persist(LS.mastery,state.mastery);
  }
  function overallMastery(){ let c=0,t=0;Object.values(state.mastery).forEach(m=>{c+=m.correct||0;t+=m.total||0});return pct(c,t); }
  function weakTopics(limit=3){
    return allTopics().map(topic=>({topic,...masteryFor(topic)})).sort((a,b)=>{
      if(a.total===0&&b.total>0)return 1;if(b.total===0&&a.total>0)return -1;return a.pct-b.pct||b.total-a.total;
    }).slice(0,limit);
  }

  function questionKey(q){ return hash(q.q); }
  function markQuestionResult(q, correct){
    const topic=inferTopic(q); updateMastery(topic,correct); const k=questionKey(q);
    if(!correct){ const w=state.wrong[k]||{q:q.q,topic,e:q.e,count:0,last:0};w.count++;w.last=Date.now();state.wrong[k]=w; }
    else if(state.wrong[k]){ state.wrong[k].count--; if(state.wrong[k].count<=0)delete state.wrong[k]; }
    persist(LS.wrong,state.wrong);
  }

  function flashCards(){ return D.flashcards.map((x,i)=>({id:hash(x[0]),i,q:x[0],a:x[1],topic:inferTopic(x[0]+' '+x[1])})); }
  function reviewRec(id){ return state.review[id] || null; }
  function reviewStats(){
    const cards=flashCards(), ts=now(); let due=0, learned=0, fresh=0;
    cards.forEach(c=>{const r=reviewRec(c.id);if(!r)fresh++;else{learned++;if((r.due||0)<=ts)due++;}});return {due,learned,fresh,total:cards.length};
  }
  function scheduleCard(card,rating){
    const old=reviewRec(card.id)||{reps:0,interval:0,ease:2.5,due:0}; const r={...old};
    if(rating==='again'){r.reps=0;r.interval=10/(24*60);r.ease=Math.max(1.3,r.ease-.2);r.due=now()+10*60*1000;}
    if(rating==='hard'){r.reps+=1;r.interval=r.interval?Math.max(1,r.interval*1.2):1;r.ease=Math.max(1.3,r.ease-.1);r.due=now()+r.interval*dayMs;}
    if(rating==='good'){r.reps+=1;r.interval=r.interval?Math.max(2,r.interval*2.2):2;r.due=now()+r.interval*dayMs;}
    if(rating==='easy'){r.reps+=1;r.interval=r.interval?Math.max(5,r.interval*3.2):5;r.ease=Math.min(3.2,r.ease+.15);r.due=now()+r.interval*dayMs;}
    r.last=now();r.lastRating=rating;state.review[card.id]=r;persist(LS.review,state.review);
    updateMastery(card.topic,rating!=='again');
  }
  function dueText(ts){ if(!ts)return 'nytt kort'; const d=Math.ceil((ts-now())/dayMs); if(d<=0)return 'nu'; if(d===1)return 'imorgon'; return `om ${d} dagar`; }

  function saveDone(){persist(LS.done,[...state.done]);updateProgress();}
  function updateProgress(){const total=D.modules.length,n=state.done.size,p=Math.round(n/total*100);$('#progressPct').textContent=p+'%';$('#progressText').textContent=`${n} av ${total} moduler klara`;$('#progressRing').style.setProperty('--p',`${p*3.6}deg`);}
  updateProgress();
  function setActiveNav(name){$$('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));}
  function navigate(route,push=true){clearTimers();if(push)location.hash=route;render(route.replace(/^#/,''));window.scrollTo({top:0,behavior:'smooth'});}
  function heroArt(file,alt=''){return `<div class="hero-art"><img src="${file}" alt="${esc(alt)}"></div>`;}
  function sourceChips(list){return `<div class="tagrow source-row">${(list||[]).map(s=>`<span class="source-chip">▣ ${esc(s)}</span>`).join('')}</div>`;}


  function goalKey(id,i){return `${id}:${i}`;}
  function goalDone(id,i){return !!state.goals[goalKey(id,i)];}
  function goalStats(goal){const total=goal.concrete.length,done=goal.concrete.filter((_,i)=>goalDone(goal.id,i)).length;return {done,total,pct:pct(done,total)};}
  function allGoalStats(){let done=0,total=0;D.learningGoals.forEach(g=>{const x=goalStats(g);done+=x.done;total+=x.total;});return {done,total,pct:pct(done,total)};}
  function praxisTypeNote(type){return type==='PREJUDIKAT'?'Vägledande avgörande från högsta instans.':type==='JO'?'Tillsynsbeslut – viktigt för myndighetsutövning men inte prejudikat.':'Extern rättskälla.';}

  function home(){
    setActiveNav('home'); const rs=reviewStats(), weak=weakTopics(3), last=state.exams[0];
    const next=D.modules.find(m=>!state.done.has(m.id))||D.modules[0];
    main.innerHTML=`<div class="page">
      <section class="hero dashboard-hero"><div><span class="eyebrow">${esc(D.course.code)} · Studieportal V3</span><h1>Plugga på det du <em>inte kan än.</em></h1><p>Portalen följer din lokala progression, bygger repetitionsintervall och pekar ut svaga områden. All data stannar i den här webbläsaren.</p><div class="actions"><button class="btn gold" data-nav="review">Starta dagens repetition</button><button class="btn alt" data-nav="exam">Starta tentaträning</button><button class="btn alt" data-nav="goals">Lärandemål</button><button class="btn alt" data-nav="praxis">Praxis</button></div><div class="callout warn"><strong>Studieverktyg – inte operativt beslutsstöd.</strong> ${esc(D.course.disclaimer)}</div></div>${heroArt('brain.svg','Abstrakt illustration av hjärna och lärande')}</section>
      <section class="stats stats-v2"><div class="stat"><b>${overallMastery()}%</b><span>uppmätt kunskapsnivå</span></div><div class="stat"><b>${rs.due}</b><span>kort att repetera nu</span></div><div class="stat"><b>${streak()}</b><span>dagars studiestreak</span></div><div class="stat"><b>${Object.keys(state.wrong).length}</b><span>frågor i fellistan</span></div></section>
      <div class="section-head"><div><span class="eyebrow">Rekommenderat idag</span><h2>Din studieplan</h2></div><p>Prioriteras från repetition och tidigare svar.</p></div>
      <div class="recommend-grid">
        <article class="card focus-card"><span class="mini-icon">↻</span><div><small>Repetition</small><h3>${rs.due?`${rs.due} förfallna kort`:`Lär in ${Math.min(8,rs.fresh)} nya kort`}</h3><p>${rs.due?'Börja med det som är dags att återkalla.':'Du är ikapp – bygg nästa lager av minnet.'}</p><button class="text-link" data-nav="review">Öppna repetition →</button></div></article>
        <article class="card focus-card"><span class="mini-icon">✓</span><div><small>Tentamen</small><h3>${last?`Senast: ${last.score}/${last.total}`:'Gör en första nulägesmätning'}</h3><p>${last?`${last.pct}% rätt · ${new Date(last.at).toLocaleDateString('sv-SE')}`:'Ett blandat test ger portalen data om vilka områden som behöver mer tid.'}</p><button class="text-link" data-nav="exam">Öppna tentamensmotor →</button></div></article>
        <article class="card focus-card"><span class="mini-icon">◇</span><div><small>Tillämpning</small><h3>1 flerstegscase</h3><p>Träna ordningen säkerhet → observation → juridik → kommunikation → överlämning.</p><button class="text-link" data-nav="cases">Öppna case-tränaren →</button></div></article>
      </div>
      <div class="section-head"><div><span class="eyebrow">Kunskapskarta</span><h2>Vad behöver mest repetition?</h2></div></div>
      <div class="mastery-grid">${allTopics().map(t=>masteryBar(t)).join('')}</div>
      <div class="section-head"><div><span class="eyebrow">Svagast just nu</span><h2>Fokusera här</h2></div></div>
      <div class="grid cols3">${weak.map(w=>`<article class="card"><span class="tag">${w.total?`${w.pct}% rätt`:'Ej testad'}</span><h3>${esc(topicMeta(w.topic).label)}</h3><p>${w.total?`${w.correct} rätt av ${w.total} registrerade svar.`:'Du har ännu inte skapat tillräckligt med data här.'}</p><div class="actions"><button class="btn small" data-exam-topic="${esc(w.topic)}">Träna området</button></div></article>`).join('')}</div>
      <div class="section-head"><div><span class="eyebrow">Fortsätt kursen</span><h2>Nästa modul</h2></div></div>${moduleCard(next)}
    </div>`;
    bindDynamic(); $$('[data-exam-topic]').forEach(b=>b.onclick=()=>{location.hash='exam';state.prefExamTopic=b.dataset.examTopic;exam();});
  }
  function masteryBar(topic){const m=masteryFor(topic);return `<div class="mastery-row"><div><strong>${esc(topicMeta(topic).label)}</strong><small>${m.total?`${m.correct}/${m.total} rätt`:'ej testad'}</small></div><div class="mastery-track"><span style="width:${m.total?Math.max(4,m.pct):0}%"></span></div><b>${m.total?m.pct+'%':'—'}</b></div>`;}

  function moduleCard(m){const done=state.done.has(m.id);return `<article class="card hover module-card" style="--accent:${m.accent}" data-open-module="${m.id}"><div class="tagrow"><span class="tag">${m.icon} ${esc(m.level)}</span><span class="tag">${esc(m.time)}</span></div><h3>${esc(m.title)}</h3><p>${esc(m.intro)}</p><div class="meta"><span>${m.tags.slice(0,2).map(x=>'#'+x).join(' ')}</span>${done?'<span class="check">✓ Klar</span>':'<span class="subtle">Öppna →</span>'}</div></article>`;}
  function modules(){setActiveNav('modules');main.innerHTML=`<div class="page"><span class="eyebrow">Hela kurskartan</span><h1 class="page-title">Alla moduler</h1><p class="subtle">Teorin är fortfarande basen. V3 kopplar dessutom teorin till kursens lärandemål och verklig praxis från officiella rättskällor.</p><div class="filterbar" id="moduleFilters"><button class="active" data-filter="Alla">Alla</button>${[...new Set(D.modules.map(m=>m.level))].map(x=>`<button data-filter="${x}">${x}</button>`).join('')}</div><div class="grid cols3" id="moduleGrid">${D.modules.map(moduleCard).join('')}</div></div>`;$('#moduleFilters').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#moduleFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;$('#moduleGrid').innerHTML=D.modules.filter(m=>f==='Alla'||m.level===f).map(moduleCard).join('');bindDynamic();};bindDynamic();}
  function modulePage(id){const m=moduleById(id);if(!m)return modules();setActiveNav('modules');const done=state.done.has(id),idx=D.modules.findIndex(x=>x.id===id),prev=D.modules[idx-1],next=D.modules[idx+1];main.innerHTML=`<div class="page module-layout"><article class="module-content"><span class="eyebrow">Modul ${m.order} · ${esc(m.level)} · ${esc(m.time)}</span><h1>${m.icon} ${esc(m.title)}</h1><p class="subtle lead">${esc(m.intro)}</p><div class="tagrow">${m.tags.map(x=>`<span class="tag">#${esc(x)}</span>`).join('')}</div><div class="callout"><strong>Efter modulen ska du kunna:</strong><ul>${m.goals.map(g=>`<li>${esc(g)}</li>`).join('')}</ul></div>${m.sections.map((s,i)=>`<section id="sec-${i}"><h2>${esc(s.h)}</h2>${s.p?`<p>${esc(s.p)}</p>`:''}${s.bullets?`<ul>${s.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>`:''}</section>`).join('')}<div class="callout warn"><strong>Minneskrok:</strong> ${esc(m.memory)}</div><div class="card"><strong>Kurskälla</strong>${sourceChips(m.source)}</div><div class="actions module-nav"><div>${prev?`<button class="btn alt" data-open-module="${prev.id}">← ${esc(prev.title)}</button>`:''}</div><div>${next?`<button class="btn" data-open-module="${next.id}">${esc(next.title)} →</button>`:''}</div></div></article><aside class="module-toc card"><strong>I den här modulen</strong>${m.sections.map((s,i)=>`<button data-scroll="sec-${i}">${i+1}. ${esc(s.h)}</button>`).join('')}<hr><button class="btn ${done?'alt':''}" id="completeModule">${done?'✓ Markerad som klar':'Markera som klar'}</button></aside></div>`;$('#completeModule').onclick=()=>{state.done.has(id)?state.done.delete(id):state.done.add(id);saveDone();toast(state.done.has(id)?'Modulen markerad som klar':'Markering borttagen');modulePage(id);};$$('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll).scrollIntoView({behavior:'smooth',block:'start'}));bindDynamic();}

  function symptom(){setActiveNav('symptom');const tones=['Alla',...new Set(D.symptomGroups.map(x=>x.tone))];main.innerHTML=`<div class="page"><section class="hero compact-hero"><div><span class="eyebrow">Jämför mönster</span><h1>Symtomkompassen</h1><p>Träna igenkänning utan att låsa dig vid en diagnos eller ett preparat. Helhet, medicinsk risk och rättslig grund måste bedömas separat.</p></div>${heroArt('drugs.svg','Abstrakt illustration av observation och drogtecken')}</section><div class="filterbar" id="symFilters">${tones.map((x,i)=>`<button class="${i?'':'active'}" data-filter="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="symptom-grid" id="symGrid">${symCards(D.symptomGroups)}</div></div>`;$('#symFilters').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#symFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;$('#symGrid').innerHTML=symCards(D.symptomGroups.filter(x=>f==='Alla'||x.tone===f));};}
  function symCards(arr){return arr.map(x=>`<article class="sym-card"><span class="tag">${esc(x.tone)}</span><h3>${esc(x.name)}</h3><ul>${x.clues.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><div class="callout mini"><strong>Bemötande/fokus:</strong><br>${esc(x.meet)}</div></article>`).join('');}

  function laws(){setActiveNav('laws');const cats=['Alla',...new Set(D.laws.map(l=>l.cat))];main.innerHTML=`<div class="page"><section class="hero compact-hero"><div><span class="eyebrow">Juridisk repetition</span><h1>Lagrumsbanken</h1><p>Fokusera på vad bestämmelsen gör och hur kursmaterialet placerar den i det polisiära flödet.</p><div class="callout warn">Lagrum återges i kursens form. Kontrollera alltid aktuell lagtext och rutin vid skarp tillämpning.</div><div class="actions"><button class="btn" data-nav="lawguide">Öppna interaktiv lagguide</button></div></div>${heroArt('law.svg','Abstrakt juridikillustration')}</section><div class="filterbar" id="lawFilters">${cats.map((x,i)=>`<button class="${i?'':'active'}" data-filter="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="grid" id="lawGrid">${lawCards(D.laws)}</div></div>`;$('#lawFilters').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#lawFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;$('#lawGrid').innerHTML=lawCards(D.laws.filter(l=>f==='Alla'||l.cat===f));};bindDynamic();}
  function lawCards(arr){return arr.map(l=>`<article class="card law-card"><div class="law-ref">${esc(l.ref)}</div><div><span class="tag">${esc(l.cat)}</span><h3>${esc(l.title)}</h3><p>${esc(l.text)}</p></div><span class="law-dot">§</span></article>`).join('');}

  function lawguide(){setActiveNav('lawguide');main.innerHTML=`<div class="page"><section class="hero compact-hero"><div><span class="eyebrow">Beslutsträd för repetition</span><h1>Interaktiv lagguide</h1><p>Välj ett rättsområde och svara dig genom rekvisiten. Guiden är avsiktligt byggd som <strong>studielogik</strong>, inte som ett skarpt beslutsstöd.</p><div class="callout warn"><strong>Viktigt:</strong> träden bygger endast på uppladdat kursmaterial och förenklar verkliga situationer för inlärning.</div></div>${heroArt('law.svg','Illustration för juridiska beslutsträd')}</section><div class="grid cols2">${D.lawGuides.map(g=>`<article class="card hover guide-card" data-open-guide="${g.id}"><span class="guide-icon">${g.icon}</span><span class="tag">Beslutsträd</span><h3>${esc(g.title)}</h3><p>${esc(g.intro)}</p>${sourceChips(g.source)}<button class="btn small">Starta guide →</button></article>`).join('')}</div></div>`;$$('[data-open-guide]').forEach(b=>b.onclick=()=>navigate('lawguide/'+b.dataset.openGuide));}
  function lawguideRun(id){setActiveNav('lawguide');const g=D.lawGuides.find(x=>x.id===id);if(!g)return lawguide();if(!state.guideRun||state.guideRun.id!==id)state.guideRun={id,node:g.start,path:[]};renderGuideNode(g);}
  function renderGuideNode(g){const run=state.guideRun,n=g.nodes[run.node];if(!n)return lawguide();if(n.end){main.innerHTML=`<div class="page guide-shell"><button class="back-link" data-nav="lawguide">← Alla lagguider</button><span class="eyebrow">${esc(g.title)}</span><div class="guide-result card"><span class="result-badge">Studieutfall</span><h1>${esc(n.status)}</h1><p>${esc(n.text)}</p><div class="path-list"><strong>Din väg</strong>${run.path.map((p,i)=>`<div><span>${i+1}</span><p>${esc(p.q)}<b>${p.answer?'Ja':'Nej'}</b></p></div>`).join('')}</div>${sourceChips(g.source)}<div class="actions"><button class="btn" id="restartGuide">Kör igen</button><button class="btn alt" data-nav="laws">Öppna lagrumsbanken</button></div></div></div>`;$('#restartGuide').onclick=()=>{state.guideRun={id:g.id,node:g.start,path:[]};renderGuideNode(g);};bindDynamic();return;}
    main.innerHTML=`<div class="page guide-shell"><button class="back-link" data-nav="lawguide">← Alla lagguider</button><span class="eyebrow">${esc(g.title)}</span><div class="guide-progress"><span style="width:${Math.min(90,12+run.path.length*20)}%"></span></div><article class="guide-question card"><span class="step-count">Steg ${run.path.length+1}</span><h1>${esc(n.q)}</h1><p>${esc(n.help||'')}</p><div class="binary-actions"><button class="choice-yes" data-guide-answer="yes">Ja</button><button class="choice-no" data-guide-answer="no">Nej</button></div></article>${sourceChips(g.source)}</div>`;$$('[data-guide-answer]').forEach(b=>b.onclick=()=>{const yes=b.dataset.guideAnswer==='yes';run.path.push({q:n.q,answer:yes});run.node=yes?n.yes:n.no;renderGuideNode(g);});bindDynamic();}

  function review(){setActiveNav('review');state.reviewRun=null;const s=reviewStats(),weak=weakTopics(1)[0];main.innerHTML=`<div class="page"><section class="hero compact-hero"><div><span class="eyebrow">Spaced repetition</span><h1>Smart repetition</h1><p>Korten schemaläggs efter hur lätt du minns dem. <strong>Igen</strong> kommer snabbt tillbaka; <strong>Bra</strong> och <strong>Lätt</strong> flyttas längre fram.</p></div>${heroArt('brain.svg','Illustration för minne och repetition')}</section><section class="stats"><div class="stat"><b>${s.due}</b><span>förfallna nu</span></div><div class="stat"><b>${s.fresh}</b><span>nya kort</span></div><div class="stat"><b>${s.learned}</b><span>kort påbörjade</span></div><div class="stat"><b>${s.total}</b><span>kort totalt</span></div></section><div class="review-options grid cols3"><article class="card"><span class="tag">Rekommenderat</span><h3>Dagens 10</h3><p>Förfallna kort först, därefter nya kort tills du har tio.</p><button class="btn" data-review-mode="daily">Starta</button></article><article class="card"><span class="tag">Fokuserat</span><h3>Svagt område</h3><p>${weak?`Prioritera ${esc(topicMeta(weak.topic).label)} utifrån dina registrerade svar.`:'Bygg först lite resultatdata.'}</p><button class="btn" data-review-mode="weak">Starta</button></article><article class="card"><span class="tag">Alla</span><h3>Blanda kort</h3><p>En slumpad runda på 20 kort från hela kursen.</p><button class="btn alt" data-review-mode="random">Starta</button></article></div><div class="callout"><strong>Hur schemat fungerar:</strong> Igen ≈ 10 minuter · Svårt ≈ 1 dag · Bra ≈ 2+ dagar · Lätt ≈ 5+ dagar. Intervallen växer när du fortsätter minnas rätt.</div></div>`;$$('[data-review-mode]').forEach(b=>b.onclick=()=>startReview(b.dataset.reviewMode));}
  function startReview(mode){const cards=flashCards(),ts=now(),due=shuffle(cards.filter(c=>reviewRec(c.id)&&(reviewRec(c.id).due||0)<=ts)),fresh=shuffle(cards.filter(c=>!reviewRec(c.id)));let items=[];if(mode==='daily')items=[...due,...fresh].slice(0,10);if(mode==='random')items=shuffle(cards).slice(0,Math.min(20,cards.length));if(mode==='weak'){const w=weakTopics(1)[0]?.topic;items=shuffle(cards.filter(c=>c.topic===w));if(items.length<10)items=[...items,...shuffle(cards.filter(c=>c.topic!==w))];items=items.slice(0,10);}if(!items.length)items=shuffle(cards).slice(0,10);state.reviewRun={mode,items,i:0,flipped:false};renderReviewCard();}
  function renderReviewCard(){setActiveNav('review');const r=state.reviewRun;if(!r||r.i>=r.items.length)return finishReview();const c=r.items[r.i],rec=reviewRec(c.id);main.innerHTML=`<div class="page review-shell"><div class="quiz-top"><span class="eyebrow">Smart repetition · ${esc(topicMeta(c.topic).label)}</span><strong>${r.i+1} / ${r.items.length}</strong></div><div class="quiz-progress"><span style="width:${r.i/r.items.length*100}%"></span></div><div class="flash-wrap"><div class="flashcard ${r.flipped?'flipped':''}" id="reviewCard"><div class="flash-inner"><div class="flash-face front"><span class="kicker">Fråga</span><h2>${esc(c.q)}</h2><small class="subtle">Klicka för att visa svaret</small></div><div class="flash-face back"><span class="kicker">Svar</span><p>${esc(c.a)}</p></div></div></div><div id="reviewControls" class="review-controls">${r.flipped?ratingButtons():`<button class="btn" id="showAnswer">Visa svar</button>`}</div><div class="review-meta"><span>${rec?`Senaste intervall: ${Math.max(1,Math.round(rec.interval||0))} dag(ar)`:'Nytt kort'}</span><span>${rec?`Planerat: ${dueText(rec.due)}`:'Ej schemalagt ännu'}</span></div></div></div>`;$('#reviewCard').onclick=()=>{r.flipped=true;renderReviewCard();};const show=$('#showAnswer');if(show)show.onclick=e=>{e.stopPropagation();r.flipped=true;renderReviewCard();};$$('[data-rating]').forEach(b=>b.onclick=e=>{e.stopPropagation();scheduleCard(c,b.dataset.rating);r.i++;r.flipped=false;renderReviewCard();});}
  function ratingButtons(){return `<div class="rating-grid"><button data-rating="again"><b>Igen</b><small>≈ 10 min</small></button><button data-rating="hard"><b>Svårt</b><small>≈ 1 dag</small></button><button data-rating="good"><b>Bra</b><small>≈ 2+ dagar</small></button><button data-rating="easy"><b>Lätt</b><small>≈ 5+ dagar</small></button></div>`;}
  function finishReview(){const n=state.reviewRun?.items.length||0;state.reviewRun=null;main.innerHTML=`<div class="page finish-screen"><span class="eyebrow">Repetition klar</span><h1>${n} kort genomförda</h1><p>Intervallen är uppdaterade. Nästa repetition kommer automatiskt när korten förfaller.</p><div class="actions"><button class="btn" data-nav="review">Se repetitionsöversikten</button><button class="btn alt" data-nav="home">Till dashboard</button></div></div>`;bindDynamic();}

  function exam(){setActiveNav('exam');clearTimers();const topicOptions=['Alla',...allTopics()];const pref=state.prefExamTopic||'Alla';state.prefExamTopic=null;const last=state.exams[0];main.innerHTML=`<div class="page"><section class="hero compact-hero"><div><span class="eyebrow">${D.quiz.length} frågor i frågebanken</span><h1>Tentamensmotor</h1><p>Välj längd, område och om du vill ha ett rent tentamensläge eller direkt återkoppling. Tiderna är <strong>övningstider</strong>, inte kursens officiella tentamenstid.</p></div>${heroArt('law.svg','Illustration för tentamen och juridik')}</section><div class="exam-setup"><section class="card"><h3>1. Frågor</h3><div class="segmented" id="examLength"><button data-val="10">10</button><button class="active" data-val="20">20</button><button data-val="30">30</button><button data-val="all">Alla</button></div></section><section class="card"><h3>2. Område</h3><select id="examTopic">${topicOptions.map(t=>`<option value="${esc(t)}" ${t===pref?'selected':''}>${t==='Alla'?'Blandat':esc(topicMeta(t).label)}</option>`).join('')}</select><label class="checkline"><input type="checkbox" id="weakFirst"> Prioritera svaga områden i blandade test</label></section><section class="card"><h3>3. Läge</h3><div class="segmented" id="examMode"><button class="active" data-val="exam">Tentamen</button><button data-val="training">Träning</button></div><small class="subtle">Tentamen visar facit först efter sista frågan.</small></section><section class="card"><h3>4. Tid</h3><div class="segmented" id="examTime"><button class="active" data-val="0">Ingen</button><button data-val="2700">45 min</button><button data-val="3600">60 min</button></div></section></div><div class="actions"><button class="btn gold big" id="startExam">Starta testet</button>${Object.keys(state.wrong).length?`<button class="btn alt" id="retryWrong">Träna mina ${Object.keys(state.wrong).length} felfrågor</button>`:''}</div>${last?`<div class="callout"><strong>Senaste test:</strong> ${last.score}/${last.total} (${last.pct}%) · ${new Date(last.at).toLocaleString('sv-SE')}</div>`:''}<div class="section-head"><div><span class="eyebrow">Ditt resultat per område</span><h2>Kunskapskartan</h2></div></div><div class="mastery-grid">${allTopics().map(masteryBar).join('')}</div></div>`;
    setupSegment('#examLength');setupSegment('#examMode');setupSegment('#examTime');$('#startExam').onclick=()=>{const len=$('#examLength .active').dataset.val,topic=$('#examTopic').value,mode=$('#examMode .active').dataset.val,time=+$('#examTime .active').dataset.val,weak=$('#weakFirst').checked;startExam({len,topic,mode,time,weak});};const rw=$('#retryWrong');if(rw)rw.onclick=()=>startWrongExam();}
  function setupSegment(sel){$(sel).onclick=e=>{const b=e.target.closest('button');if(!b)return;$$(sel+' button').forEach(x=>x.classList.remove('active'));b.classList.add('active');};}
  function buildExamPool(topic,weak){let pool=D.quiz.map(q=>({...q,topic:inferTopic(q)}));if(topic!=='Alla')pool=pool.filter(q=>q.topic===topic);if(weak&&topic==='Alla'){const order=new Map(allTopics().sort((a,b)=>masteryFor(a).pct-masteryFor(b).pct).map((t,i)=>[t,i]));pool=shuffle(pool).sort((a,b)=>(order.get(a.topic)||0)-(order.get(b.topic)||0));}else pool=shuffle(pool);return pool;}
  function startExam(cfg){let pool=buildExamPool(cfg.topic,cfg.weak),n=cfg.len==='all'?pool.length:Math.min(+cfg.len,pool.length);state.exam={items:pool.slice(0,n),answers:Array(n).fill(null),i:0,mode:cfg.mode,duration:cfg.time,ends:cfg.time?Date.now()+cfg.time*1000:0,feedback:false};renderExamQuestion();}
  function startWrongExam(){const wrongQs=Object.values(state.wrong);let items=wrongQs.map(w=>D.quiz.find(q=>q.q===w.q)).filter(Boolean).map(q=>({...q,topic:inferTopic(q)}));if(!items.length){toast('Fellistan är redan tom.');return;}state.exam={items:shuffle(items),answers:Array(items.length).fill(null),i:0,mode:'training',duration:0,ends:0,feedback:false};renderExamQuestion();}
  function startExamTimer(){if(!state.exam?.ends)return;const tick=()=>{const el=$('#examTimer');if(!el)return;const sec=Math.max(0,Math.floor((state.exam.ends-Date.now())/1000)),m=Math.floor(sec/60),s=sec%60;el.textContent=`${m}:${String(s).padStart(2,'0')}`;if(sec<=0){clearTimers();finishExam(true);}};tick();const id=setInterval(tick,1000);state.timers.push(id);}
  function renderExamQuestion(){clearTimers();const z=state.exam;if(!z)return exam();if(z.i>=z.items.length)return finishExam(false);const q=z.items[z.i],selected=z.answers[z.i];main.innerHTML=`<div class="page quiz-shell"><div class="quiz-top"><span class="eyebrow">${z.mode==='exam'?'Tentamensläge':'Träningsläge'} · ${esc(topicMeta(q.topic).label)}</span><div><strong>${z.i+1} / ${z.items.length}</strong>${z.ends?`<span class="timer" id="examTimer"></span>`:''}</div></div><div class="quiz-progress"><span style="width:${z.i/z.items.length*100}%"></span></div><h2 class="question">${esc(q.q)}</h2><div class="answers">${q.a.map((a,i)=>`<button class="answer ${selected===i?'selected':''}" data-answer="${i}" ${z.feedback?'disabled':''}>${String.fromCharCode(65+i)}. ${esc(a)}</button>`).join('')}</div><div id="examFeedback">${z.feedback?trainingFeedback(q,selected):''}</div><div class="exam-nav">${z.i>0&&!z.feedback&&z.mode==='exam'?'<button class="btn alt" id="prevExam">← Föregående</button>':'<span></span>'}<button class="btn" id="nextExam" ${selected===null?'disabled':''}>${z.feedback?'Nästa fråga →':z.i===z.items.length-1?'Lämna in':'Nästa →'}</button></div></div>`;
    $$('.answer').forEach(b=>b.onclick=()=>{if(z.feedback)return;z.answers[z.i]=+b.dataset.answer;if(z.mode==='training'){z.feedback=true;renderExamQuestion();}else renderExamQuestion();});const nx=$('#nextExam');nx.onclick=()=>{if(z.answers[z.i]===null)return;if(z.mode==='training'&&z.feedback){z.feedback=false;z.i++;renderExamQuestion();}else if(z.i===z.items.length-1){finishExam(false);}else{z.i++;renderExamQuestion();}};const pv=$('#prevExam');if(pv)pv.onclick=()=>{z.i--;renderExamQuestion();};startExamTimer();}
  function trainingFeedback(q,sel){const ok=sel===q.c;return `<div class="explain ${ok?'ok':'bad'}"><strong>${ok?'✓ Rätt':'✕ Inte riktigt'}</strong><p>${esc(q.e)}</p><small>Kurskälla: ${esc(q.source||topicMeta(q.topic).source)}</small></div>`;}
  function finishExam(timedOut){clearTimers();const z=state.exam;if(!z)return exam();let score=0;const breakdown={};z.items.forEach((q,i)=>{const ok=z.answers[i]===q.c;if(ok)score++;const t=q.topic||inferTopic(q);breakdown[t]=breakdown[t]||{c:0,n:0};breakdown[t].n++;if(ok)breakdown[t].c++;markQuestionResult(q,ok);});const p=pct(score,z.items.length),rec={at:Date.now(),score,total:z.items.length,pct:p,mode:z.mode,timedOut};state.exams.unshift(rec);state.exams=state.exams.slice(0,20);persist(LS.exams,state.exams);const wrong=z.items.map((q,i)=>({q,sel:z.answers[i],ok:z.answers[i]===q.c})).filter(x=>!x.ok);state.exam=null;main.innerHTML=`<div class="page results-page"><span class="eyebrow">${timedOut?'Tiden gick ut':'Test inlämnat'}</span><div class="score-hero"><div class="score-ring" style="--score:${p*3.6}deg"><span><b>${p}%</b><small>${score}/${rec.total}</small></span></div><div><h1>${p>=80?'Stabil nivå.':p>=60?'Bra – nu syns luckorna.':'Bygg grunden och testa igen.'}</h1><p>Resultatet har sparats lokalt och påverkar dashboardens rekommendationer.</p></div></div><div class="section-head"><div><span class="eyebrow">Per område</span><h2>Resultatprofil</h2></div></div><div class="mastery-grid">${Object.entries(breakdown).map(([t,b])=>`<div class="mastery-row"><div><strong>${esc(topicMeta(t).label)}</strong><small>${b.c}/${b.n} rätt</small></div><div class="mastery-track"><span style="width:${pct(b.c,b.n)}%"></span></div><b>${pct(b.c,b.n)}%</b></div>`).join('')}</div>${wrong.length?`<div class="section-head"><div><span class="eyebrow">Återkoppling</span><h2>Frågor att repetera</h2></div><p>${wrong.length} fel / obesvarade</p></div><div class="wrong-list">${wrong.map((x,i)=>`<details class="card"><summary><span>${i+1}</span>${esc(x.q.q)}</summary><div class="wrong-body"><p><strong>Ditt svar:</strong> ${x.sel===null?'Obesvarad':esc(x.q.a[x.sel])}</p><p><strong>Rätt svar:</strong> ${esc(x.q.a[x.q.c])}</p><p>${esc(x.q.e)}</p><small>Kurskälla: ${esc(x.q.source||topicMeta(x.q.topic).source)}</small></div></details>`).join('')}</div>`:`<div class="callout"><strong>Alla rätt.</strong> Fellistan har inget nytt från den här rundan.</div>`}<div class="actions"><button class="btn" data-nav="exam">Ny tentamen</button><button class="btn alt" data-nav="review">Repetera kort</button><button class="btn alt" data-nav="home">Dashboard</button></div></div>`;bindDynamic();}

  function cases(){setActiveNav('cases');main.innerHTML=`<div class="page"><section class="hero compact-hero"><div><span class="eyebrow">Flerstegsbeslut</span><h1>Case-tränare</h1><p>Varje case går i flera steg. Du tränar inte ett magiskt facit, utan en <strong>ordningsföljd</strong>: säkerhet → observation → rättslig grund → kommunikation → överlämning.</p></div>${heroArt('dialogue.svg','Illustration av polisiärt samtal')}</section><div class="grid cols2">${D.caseScenarios.map(c=>{const h=state.caseHistory[c.id];return `<article class="card hover case-launch" data-open-case="${c.id}"><div class="tagrow"><span class="tag">${esc(c.difficulty)}</span><span class="tag">${c.steps.length} steg</span>${h?`<span class="tag success">Bäst ${h.best}/${c.steps.length}</span>`:''}</div><h3>${esc(c.title)}</h3><p>${esc(c.scenario)}</p><div class="case-facts">${c.facts.slice(0,4).map(f=>`<div class="case-fact">${esc(f)}</div>`).join('')}</div><button class="btn small">${h?'Kör igen':'Starta case'} →</button></article>`}).join('')}</div></div>`;$$('[data-open-case]').forEach(b=>b.onclick=()=>navigate('case/'+b.dataset.openCase));}
  function caseRun(id){setActiveNav('cases');const c=D.caseScenarios.find(x=>x.id===id);if(!c)return cases();if(!state.caseRun||state.caseRun.id!==id)state.caseRun={id,step:0,score:0,answered:false};renderCaseStep(c);}
  function renderCaseStep(c){const r=state.caseRun;if(r.step>=c.steps.length)return finishCase(c);const s=c.steps[r.step];main.innerHTML=`<div class="page case-shell"><button class="back-link" data-nav="cases">← Alla case</button><div class="case-header"><div><span class="eyebrow">${esc(c.difficulty)} · ${r.step+1}/${c.steps.length}</span><h1>${esc(c.title)}</h1></div><div class="case-score">${r.score}<small>poäng</small></div></div><div class="quiz-progress"><span style="width:${r.step/c.steps.length*100}%"></span></div><article class="scenario-card"><p>${esc(c.scenario)}</p><div class="case-facts">${c.facts.map(f=>`<div class="case-fact">${esc(f)}</div>`).join('')}</div></article><article class="card decision-card"><span class="phase">${esc(s.phase)}</span><h2>${esc(s.prompt)}</h2><div class="case-options">${s.choices.map((o,i)=>`<button class="case-option" data-case-choice="${i}">${esc(o.t)}</button>`).join('')}</div><div id="caseFeedback"></div></article>${sourceChips(c.source)}</div>`;$$('[data-case-choice]').forEach(b=>b.onclick=()=>{if(r.answered)return;r.answered=true;const idx=+b.dataset.caseChoice,o=s.choices[idx];if(o.ok)r.score++;updateMastery(c.topic,o.ok);$$('[data-case-choice]').forEach((x,i)=>{x.disabled=true;if(s.choices[i].ok)x.classList.add('correct');if(i===idx&&!o.ok)x.classList.add('wrong');});$('#caseFeedback').innerHTML=`<div class="explain ${o.ok?'ok':'bad'}"><strong>${o.ok?'✓ Bra resonemang':'↺ Tänk ett varv till'}</strong><p>${esc(o.why)}</p><button class="btn" id="nextCase">${r.step===c.steps.length-1?'Visa resultat':'Nästa steg →'}</button></div>`;$('#nextCase').onclick=()=>{r.step++;r.answered=false;renderCaseStep(c);};});bindDynamic();}
  function finishCase(c){const r=state.caseRun,p=pct(r.score,c.steps.length),old=state.caseHistory[c.id]||{best:0,runs:0};old.best=Math.max(old.best,r.score);old.runs++;old.last=Date.now();state.caseHistory[c.id]=old;persist(LS.cases,state.caseHistory);state.caseRun=null;main.innerHTML=`<div class="page finish-screen"><span class="eyebrow">Case genomfört</span><h1>${r.score} / ${c.steps.length}</h1><p>${p>=80?'Du höll ihop risk, juridik och bemötande väl.':'Läs återkopplingen i minnet och kör gärna caset igen senare.'}</p><div class="callout"><strong>Ta med dig:</strong> ${esc(c.takeaway)}</div>${sourceChips(c.source)}<div class="actions"><button class="btn" data-open-case="${c.id}">Kör igen</button><button class="btn alt" data-nav="cases">Alla case</button><button class="btn alt" data-nav="home">Dashboard</button></div></div>`;$$('[data-open-case]').forEach(b=>b.onclick=()=>navigate('case/'+b.dataset.openCase));bindDynamic();}


  function goals(){
    setActiveNav('goals');
    const overall=allGoalStats(), groups=['Alla','Kunskap & förståelse','Färdighet & förmåga','Värderingsförmåga & förhållningssätt'];
    const renderCards=(items)=>items.map(g=>{const st=goalStats(g);return `<details class="card goal-card" data-goal-card="${g.id}"><summary><div class="goal-code">${esc(g.id)}</div><div class="goal-summary"><div class="tagrow">${g.examined.map(x=>`<span class="tag exam-tag">${esc(x)}</span>`).join('')}<span class="tag">${esc(g.group)}</span></div><h3>${esc(g.goal)}</h3><div class="goal-progress"><span><i style="width:${st.pct}%"></i></span><b>${st.done}/${st.total}</b></div></div><span class="goal-chevron">⌄</span></summary><div class="goal-body"><div class="callout mini"><strong>Så här har portalen konkretiserat målet</strong><p>Checklistan är en pedagogisk nedbrytning av kursmålet utifrån de uppladdade kursfilerna. Själva kursmålets formulering ovan är återgiven från studiehandledningen.</p></div><div class="goal-checklist">${g.concrete.map((item,i)=>`<label class="goal-check ${goalDone(g.id,i)?'done':''}"><input type="checkbox" data-goal-check="${g.id}" data-goal-index="${i}" ${goalDone(g.id,i)?'checked':''}><span><b>${goalDone(g.id,i)?'Kan':'Träna'}</b>${esc(item)}</span></label>`).join('')}</div>${sourceChips(g.sources)}<div class="actions goal-actions">${(g.routes||[]).map(a=>`<button class="btn alt small" data-nav="${esc(a.route)}">${esc(a.label)} →</button>`).join('')}</div></div></details>`}).join('');
    main.innerHTML=`<div class="page"><section class="hero compact-hero goals-hero"><div><span class="eyebrow">Examinationsstyrt plugg</span><h1>Lärandemål</h1><p>Här är kursmålen från studiehandledningen översatta till <strong>konkret kunskap du ska kunna visa</strong>. Kryssa bara när du själv kan förklara eller tillämpa punkten utan att titta.</p><div class="goal-overall"><div><b>${overall.pct}%</b><span>${overall.done} av ${overall.total} kunskapspunkter markerade</span></div><div class="mastery-track"><span style="width:${overall.pct}%"></span></div></div><div class="callout warn"><strong>Examinationerna:</strong> R1 = reflektionsseminarium · IN1 = inlämningsuppgift · TEN = individuell tentamen.</div></div>${heroArt('brain.svg','Illustration av lärande och progression')}</section><div class="filterbar" id="goalFilters">${groups.map((x,i)=>`<button class="${i?'':'active'}" data-filter="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="goal-list" id="goalList">${renderCards(D.learningGoals)}</div></div>`;
    $('#goalFilters').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#goalFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;$('#goalList').innerHTML=renderCards(D.learningGoals.filter(g=>f==='Alla'||g.group===f));bindGoalChecks();bindDynamic();};
    bindGoalChecks();bindDynamic();
  }
  function bindGoalChecks(){
    $$('[data-goal-check]').forEach(cb=>cb.onchange=()=>{const k=goalKey(cb.dataset.goalCheck,+cb.dataset.goalIndex);if(cb.checked)state.goals[k]=true;else delete state.goals[k];persist(LS.goals,state.goals);noteActivity();const d=cb.closest('details');const wasOpen=d?.open;goals();const nd=$(`[data-goal-card="${cb.dataset.goalCheck}"]`);if(nd&&wasOpen)nd.open=true;toast(cb.checked?'Markerat som behärskat':'Flyttat tillbaka till träning');});
  }

  function praxis(){
    setActiveNav('praxis');
    const areas=['Alla',...new Set(D.praxisCases.map(c=>c.area))], types=['Alla typer','PREJUDIKAT','JO'];
    const renderCards=(items)=>items.map(c=>`<details class="card praxis-card"><summary><div class="praxis-badge ${c.type.toLowerCase()}">${esc(c.type)}</div><div class="praxis-summary"><div class="tagrow"><span class="tag">${esc(c.area)}</span>${c.laws.slice(0,3).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><h3>${esc(c.citation)}</h3><p>${esc(c.gray)}</p><small>${esc(c.court)} · ${new Date(c.date+'T12:00:00').toLocaleDateString('sv-SE')}</small></div><span class="goal-chevron">⌄</span></summary><div class="praxis-body"><div class="praxis-grid"><div><span class="praxis-label">Situationen</span><p>${esc(c.facts)}</p></div><div><span class="praxis-label">Bedömningen</span><p>${esc(c.holding)}</p></div><div class="memory-box"><span class="praxis-label">Minnesregel</span><p>${esc(c.memory)}</p></div><div><span class="praxis-label">Polisiär betydelse</span><p>${esc(c.police)}</p></div></div><div class="praxis-footer"><small><strong>${esc(c.type)}:</strong> ${esc(praxisTypeNote(c.type))}</small><a class="btn alt small" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">Öppna originalkälla ↗</a></div></div></details>`).join('');
    const apply=()=>{const area=$('#praxisArea')?.value||'Alla', type=$('#praxisType')?.value||'Alla typer', q=($('#praxisSearch')?.value||'').trim().toLowerCase();const items=D.praxisCases.filter(c=>(area==='Alla'||c.area===area)&&(type==='Alla typer'||c.type===type)&&(!q||[c.citation,c.gray,c.facts,c.holding,c.memory,c.police,c.laws.join(' ')].join(' ').toLowerCase().includes(q)));$('#praxisList').innerHTML=items.length?renderCards(items):'<div class="empty">Inga praxisfall matchar filtret.</div>';$('#praxisCount').textContent=`${items.length} fall`;};
    main.innerHTML=`<div class="page"><section class="hero compact-hero praxis-hero"><div><span class="eyebrow">Extern rättsfallsresearch · uppdaterad ${esc(D.praxisUpdated)}</span><h1>Praxis & gråzoner</h1><p>Lagtexten ger strukturen. Här tränar du på <strong>var gränserna faktiskt har prövats</strong>: verkliga prejudikat från HD/HFD och JO-beslut med särskild betydelse för myndighetsutövning.</p><div class="callout warn"><strong>Viktigt:</strong> JO-beslut är inte prejudikat. Äldre avgöranden måste alltid läsas mot senare lagändringar. Detta är studiehjälp – kontrollera aktuell lagtext, nyare praxis och lokala föreskrifter vid skarp tillämpning.</div></div>${heroArt('law.svg','Illustration av juridik och rättspraxis')}</section><div class="praxis-toolbar"><select id="praxisArea" aria-label="Filtrera rättsområde">${areas.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="praxisType" aria-label="Filtrera källtyp">${types.map(x=>`<option>${esc(x)}</option>`).join('')}</select><input id="praxisSearch" type="search" placeholder="Sök t.ex. husrannsakan, LVM 24, vårdintyg…"><span class="tag" id="praxisCount">${D.praxisCases.length} fall</span></div><div class="callout mini"><strong>Så läser du korten:</strong> börja med gråzonen → försök svara själv → öppna kortet → jämför med bedömningen och minnesregeln. Länken går till originalkällan hos Sveriges Domstolar eller JO.</div><div class="praxis-list" id="praxisList">${renderCards(D.praxisCases)}</div></div>`;
    ['praxisArea','praxisType'].forEach(id=>$('#'+id).onchange=apply);$('#praxisSearch').oninput=apply;
  }

  function notes(){setActiveNav('notes');const val=localStorage.getItem(LS.notes)||'';main.innerHTML=`<div class="page"><span class="eyebrow">Lokalt i din webbläsare</span><h1 class="page-title">Mina anteckningar</h1><p class="subtle">Anteckningarna sparas automatiskt på den här enheten.</p><textarea class="notes-area" id="notesArea" placeholder="Skriv egna minnesregler, frågor till handledningen, case-resonemang…">${esc(val)}</textarea><div class="actions"><button class="btn alt" id="exportNotes">Exportera .txt</button><button class="btn alt" id="clearNotes">Rensa</button></div></div>`;let timer;$('#notesArea').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>{localStorage.setItem(LS.notes,e.target.value);toast('Anteckningar sparade')},500);};$('#clearNotes').onclick=()=>{if(confirm('Rensa alla anteckningar?')){$('#notesArea').value='';localStorage.removeItem(LS.notes);}};$('#exportNotes').onclick=()=>{const blob=new Blob([$('#notesArea').value],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mina-anteckningar-psykisk-ohalsa.txt';a.click();URL.revokeObjectURL(a.href);};}
  function sources(){setActiveNav('sources');main.innerHTML=`<div class="page"><span class="eyebrow">Transparens</span><h1 class="page-title">Källor & avgränsning</h1><div class="callout"><strong>Hur V3 är byggd</strong><p>Teori, lärandemålens konkreta kunskapspunkter, frågor, case och lagguider är pedagogiskt omarbetade från kursfilerna i projektet. <strong>Praxis-fliken är ett tydligt avskilt undantag:</strong> där används extern research från officiella källor hos Sveriges Domstolar och JO, och varje fall länkar till originalkällan.</p></div><div class="callout warn"><strong>Viktigt om juridiken</strong><p>Beslutsträden förenklar för att träna rekvisit. Praxisöversikterna är sammanfattningar för studier. De är inte operativa checklistor. Lagtext, praxis, beslutsnivåer, föreskrifter och lokala rutiner kan ändras.</p></div><div class="grid cols2"><div class="card"><h2>Kursfiler</h2><ul class="source-list">${D.sources.map(s=>`<li>▣ ${esc(s)}</li>`).join('')}</ul></div><div class="card"><h2>Vad sparas?</h2><p>Följande sparas endast i webbläsarens localStorage:</p><ul><li>markerade moduler</li><li>lärandemålens checklistor</li><li>flashcard-intervall</li><li>tentamensresultat och svaga områden</li><li>case-resultat</li><li>anteckningar</li></ul><p>Ingen server eller databas används.</p><button class="btn alt" id="resetProgress">Nollställ V3-studiedata</button></div></div><div class="grid cols2" style="margin-top:16px"><div class="card"><h2>Extern praxisresearch</h2><p>${D.praxisCases.length} fall från HD, HFD och JO. Researchen är daterad ${esc(D.praxisUpdated)}. Alla kort har direktlänk till originalkällan.</p><button class="btn alt" data-nav="praxis">Öppna praxis →</button></div><div class="card"><h2>Avgränsning i materialet</h2><p>Studiehandledningen nämner även suicidologi, vardagsförhandling och dödsfall. Där separat komplett underlag inte fanns bland de tillgängliga filerna har sidan inte hittat på ett fullständigt kursinnehåll. Det markeras uttryckligen i relevanta lärandemål.</p></div></div></div>`;$('#resetProgress').onclick=()=>{if(confirm('Nollställ tentamen, repetition, case, lärandemål och kunskapsdata? Moduler och anteckningar lämnas kvar.')){[LS.mastery,LS.review,LS.wrong,LS.activity,LS.exams,LS.cases,LS.goals].forEach(k=>localStorage.removeItem(k));location.reload();}};bindDynamic();}

  function searchOpen(){const o=$('#searchOverlay');o.hidden=false;setTimeout(()=>$('#searchInput').focus(),20);search('');}
  function searchClose(){$('#searchOverlay').hidden=true;}
  function search(term){const t=term.trim().toLowerCase();let results=[];D.modules.forEach(m=>{const hay=[m.title,m.intro,m.tags.join(' '),...m.sections.map(s=>s.h+' '+(s.p||'')+' '+(s.bullets||[]).join(' '))].join(' ').toLowerCase();if(!t||hay.includes(t))results.push({type:'Modul',title:m.title,sub:m.tags.join(' · '),route:'module/'+m.id});});D.laws.forEach(l=>{const hay=(l.ref+' '+l.title+' '+l.text+' '+l.cat).toLowerCase();if(t&&hay.includes(t))results.push({type:'Lagrum',title:l.ref+' – '+l.title,sub:l.cat,route:'laws'});});D.lawGuides.forEach(g=>{const hay=(g.title+' '+g.intro).toLowerCase();if(t&&hay.includes(t))results.push({type:'Lagguide',title:g.title,sub:'Interaktivt beslutsträd',route:'lawguide/'+g.id});});D.caseScenarios.forEach(c=>{const hay=(c.title+' '+c.scenario+' '+c.facts.join(' ')).toLowerCase();if(t&&hay.includes(t))results.push({type:'Case',title:c.title,sub:c.difficulty,route:'case/'+c.id});});if(t)D.quiz.filter(q=>q.q.toLowerCase().includes(t)).slice(0,5).forEach(q=>results.push({type:'Tentafråga',title:q.q,sub:topicMeta(inferTopic(q)).label,route:'exam'}));if(t)D.learningGoals.filter(g=>(g.id+' '+g.goal+' '+g.concrete.join(' ')).toLowerCase().includes(t)).slice(0,5).forEach(g=>results.push({type:'Lärandemål',title:g.id+' – '+g.goal,sub:g.examined.join(' · '),route:'goals'}));if(t)D.praxisCases.filter(c=>(c.citation+' '+c.gray+' '+c.laws.join(' ')+' '+c.holding).toLowerCase().includes(t)).slice(0,6).forEach(c=>results.push({type:'Praxis',title:c.citation,sub:c.area+' · '+c.type,route:'praxis'}));$('#searchResults').innerHTML=results.slice(0,20).map(r=>`<div class="search-result" data-search-route="${r.route}"><small>${esc(r.type)}</small><b>${esc(r.title)}</b><small>${esc(r.sub)}</small></div>`).join('')||'<div class="empty">Inga träffar.</div>';$$('[data-search-route]').forEach(x=>x.onclick=()=>{searchClose();navigate(x.dataset.searchRoute);});}

  function bindDynamic(){$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));$$('[data-open-module]').forEach(b=>b.onclick=()=>navigate('module/'+b.dataset.openModule));}
  function render(route){route=route||'home';if(route.startsWith('module/'))return modulePage(route.split('/')[1]);if(route.startsWith('lawguide/'))return lawguideRun(route.split('/')[1]);if(route.startsWith('case/'))return caseRun(route.split('/')[1]);if(route==='flashcards')route='review';if(route==='quiz')route='exam';const fn={home,modules,symptom,laws,lawguide,goals,praxis,review,exam,cases,notes,sources}[route]||home;fn();}

  bindDynamic();
  $('#searchBtn').onclick=searchOpen;$('#searchClose').onclick=searchClose;$('#searchOverlay').onclick=e=>{if(e.target===$('#searchOverlay'))searchClose();};$('#searchInput').oninput=e=>search(e.target.value);
  $('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;localStorage.setItem(LS.theme,state.theme);};
  window.addEventListener('hashchange',()=>render(location.hash.slice(1)));
  document.addEventListener('keydown',e=>{if(e.key==='/'&&!/input|textarea|select/i.test(document.activeElement.tagName)){e.preventDefault();searchOpen();}if(e.key==='Escape')searchClose();if(e.key===' '&&location.hash==='#review'&&state.reviewRun&&!/input|textarea|select|button/i.test(document.activeElement.tagName)){e.preventDefault();state.reviewRun.flipped=true;renderReviewCard();}});
  render(location.hash.slice(1)||'home');
})();
